version: '3.8'

services:
  jobthai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobthai-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python app/main.py
